# Generated by Django 5.0.4 on 2024-04-29 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtunes', '0004_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlater',
            name='video_id',
        ),
        migrations.AddField(
            model_name='watchlater',
            name='song',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mtunes.song'),
            preserve_default=False,
        ),
    ]
