# Generated by Django 5.0.4 on 2024-04-29 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtunes', '0005_remove_watchlater_video_id_watchlater_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='music_id',
        ),
        migrations.AddField(
            model_name='history',
            name='song',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mtunes.song'),
            preserve_default=False,
        ),
    ]
